name: Test action
on:
  issue_comment:
    types: [created]
jobs:
  verion-update:
    name: Taaza tazza action
    runs-on: ubuntu-latest
    steps:
      - name: Checking out code
        run: |
          echo "I am first"
      - uses: actions/checkout@v3
      - name: Listing pwd
        run: |
          ls

      - run: chmod +x updateVersion.sh
      - run: ./updateVersion.sh
      - run: git add iosVersion.txt
      - run: git -c user.name="bot" -c user.email="bot@github.com" commit -m "updated ios version"
      - run: git push origin 
