name: Test action
on:
  issue_comment:
    types: [created]
jobs:
  verion-update:
    name: Taaza tazza action
    runs-on: ubuntu-latest
    steps:
      - name: Checking out code
        uses: actions/checkout@v3
        run: |
          echo "I am first"
      - name: Listing pwd
        run: |
          ls
