name: Test action
on:
  issue_comment:
    types: [created]
jobs:
  verion-update:
    name: Taaza tazza action
    runs-on: ubuntu-latest
    steps:
      - name: Checking out code
        uses: actions/checkout@v3
        run: |
          echo "I am first"
      - name: Listing pwd
        run: |
          ls
      - name: running script
        run: |
        chmod +x updateVersion.sh
        git add iosVersion.txt
        git -c user.name="bot" user.email="bot@github.com" commit -m "updated ios version"
        git push origin 
