name: Update IOS version
on:
  workflow_dispatch:
    inputs:
      branch-name:
        description: 'Branch to update'
        required: true
        default: 'main'

jobs:
  update-version:
    name: update ios version ...
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Listing pwd
        run: |
          ls
      - run: chmod +x updateVersion.sh
      - run: ./updateVersion.sh
      - run: git add iosVersion.txt
      - run: git -c user.name="bot" -c user.email="bot@github.com" commit -m "updated ios version"
      - run: git push origin 
