name: Update Version Action
on:
  issue_comment:
    types: [created]
jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - name: Check if comment contains "update version"
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const phrase = 'update version';
            const comment = context.payload.comment.body;
            if (comment.includes(phrase)) {
              console.log(`Comment contains "${phrase}"`);
              // Run the updateVersion.sh script
              const exec = require('child_process').exec;
              exec('sh updateVersion.sh', (error, stdout, stderr) => {
                console.log(stdout);
                console.error(stderr);
                if (error !== null) {
                  console.error(`exec error: ${error}`);
                } else {
                  console.log(`Script ran successfully`);
                  // Push the updated code to the main branch
                  exec('git push origin main', (error, stdout, stderr) => {
                    console.log(stdout);
                    console.error(stderr);
                    if (error !== null) {
                      console.error(`exec error: ${error}`);
                    } else {
                      console.log(`Code pushed to main branch`);
                    }
                  });
                }
              });
            }
