name: Update Version Action
on:
  issue_comment:
    types: [created]
jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - name: Check if comment contains "update version"
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const phrase = 'update version';
            const comment = context.payload.comment.body;
            if (comment.includes(phrase)) {
              console.log(`Comment contains "${phrase}"`);
              // List files in the working directory
              const ls = require('child_process').exec;
              ls('ls', (error, stdout, stderr) => {
                console.log(stdout);
                console.error(stderr);
                if (error !== null) {
                  console.error(`ls error: ${error}`);
                } else {
                  console.log(`Files listed successfully`);
                  // Set execute permission on the script
                  const chmod = require('child_process').exec;
                  chmod('chmod +x updateVersion.sh', (error, stdout, stderr) => {
                    console.log(stdout);
                    console.error(stderr);
                    if (error !== null) {
                      console.error(`chmod error: ${error}`);
                    } else {
                      console.log(`Execute permission set on updateVersion.sh`);
                      // Run the updateVersion.sh script
                      const exec = require('child_process').exec;
                      exec('sh updateVersion.sh', (error, stdout, stderr) => {
                        console.log(stdout);
                        console.error(stderr);
                        if (error !== null) {
                          console.error(`exec error: ${error}`);
                        } else {
                          console.log(`Script ran successfully`);
                          // Push the updated code to the release branch
                          exec('git push origin release', (error, stdout, stderr) => {
                            console.log(stdout);
                            console.error(stderr);
                            if (error !== null) {
                              console.error(`exec error: ${error}`);
                            } else {
                              console.log(`Code pushed to release branch`);
                            }
                          });
                        }
                      });
                    }
                  });
                }
              });
            }
