name: Update IOS version
on:
  workflow_dispatch:

jobs:
  update-version:
    name: update ios version ...
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: chmod +x updateVersion.sh
      - run: ./updateVersion.sh
      - run: git add iosVersion.txt
      - run: git -c user.name="GitHub Actions Bot" -c user.email="41898282+github-actions[bot]@users.noreply.github.com" commit -m "updated ios version" |
          --author "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
      - run: git push origin 
